[build]
  command = "npm ci && npm run build"  # BlondeのREADME通り、Tailwind/PostCSS込みでビルド
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"   # ローカルと同じに（例）
  HUGO_ENV = "production"
  NODE_VERSION = "20"
