[build]
  command = "npm ci && npx -y tailwindcss@latest -i ./themes/Blonde/assets/css/main.css -o ./themes/Blonde/assets/css/style.css --minify && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"
  NODE_VERSION = "20"
