[build]
  command = "npm ci && npm run build && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"  # まずは現状のまま。ローカルと揃えるのがベスト
  HUGO_ENV = "production"
  NODE_VERSION = "20"
